---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alertmanager-user-workload-api-read-binding-{{ .Release.Namespace }}
  namespace: openshift-user-workload-monitoring 
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role 
  name: monitoring-alertmanager-api-reader 
  apiGroup: rbac.authorization.k8s.io