apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccountName }}
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}