# MinIO S3 credentials secret for Tempo
apiVersion: v1
kind: Secret
metadata:
  name: minio-tempo
  namespace: {{ include "tempo-stack.namespace" . }}
  labels:
    {{- include "tempo-stack.minioLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  access_key_id: {{ .Values.minio.s3.accessKeyId }}
  access_key_secret: {{ .Values.minio.s3.accessKeySecret }}
  bucket: {{ .Values.minio.s3.bucket }}
  endpoint: http://{{ .Values.minio.service.name }}.{{ include "tempo-stack.namespace" . }}.svc.cluster.local:{{ .Values.minio.service.ports.api }}
---
# MinIO root user credentials
apiVersion: v1
kind: Secret
metadata:
  name: minio-user-creds
  namespace: {{ include "tempo-stack.namespace" . }}
  labels:
    {{- include "tempo-stack.minioLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.credentials.rootUser }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.credentials.rootPassword }}