# MinIO Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-tempo
  namespace: {{ include "tempo-stack.namespace" . }}
  labels:
    {{- include "tempo-stack.minioLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storage.size }}
  {{- if .Values.minio.storage.storageClass }}
  storageClassName: {{ .Values.minio.storage.storageClass }}
  {{- end }}
  volumeMode: Filesystem