---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-thanos-{{ .Release.Namespace }}-mcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: mcp-analyzer
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-monitoring-view-thanos-{{ .Release.Namespace }}-mcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: mcp-analyzer
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-cluster-monitoring-view-thanos-{{ .Release.Namespace }}-mcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: mcp-analyzer
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.rbac.createGrafanaRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-prometheus-reader
rules:
- apiGroups: ["*"]
  resources:
    - "prometheuses"
    - "prometheuses/*"
  verbs:
    - "get"
    - "list"
    - "watch"
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-prometheus-reader-binding-{{ .Release.Namespace }}-mcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-prometheus-reader
subjects:
  - kind: ServiceAccount
    name: mcp-analyzer
    namespace: {{ .Release.Namespace }}


