kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Release.Name }}-route
spec:
  to:
    kind: Service
    name: ui
    weight: 100
  port:
    targetPort: 8501
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None