name: 'Checkout with Branch Info'
description: 'Checkout repository and display branch/commit information'
inputs:
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
  fetch-depth:
    description: 'Number of commits to fetch'
    required: false
    default: '1'
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
    
    - name: Show branch and commit info
      shell: bash
      run: |
        echo "::group::Repository Information"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Event: ${{ github.event_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "::endgroup::"