apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example-1
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
spec:
  replicas: 2
  evaluationInterval: 30s
  scrapeInterval: 30s
  serviceAccountName: prometheus-k8s
  podMonitorSelector: {}
  serviceMonitorSelector: {}
  probeSelector: {}
  ruleSelector: {}
  portName: web
