---
apiVersion: v1
kind: Secret
metadata:
  name: metric-analyzer
  namespace: {{ .Release.namespace }}
  annotations:
    kubernetes.io/service-account.name: metric-analyzer
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-analyzer
