replicaCount: 1

image:
  repository: "overridden-by-makefile"
  tag: "overridden-by-makefile"

service:
  type: ClusterIP
  port: 8000

route:
  enabled: true
  host: ai-metrics-summarizer.example.com

config:
  prometheusUrl: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"

llm:
  url: ""
  apiToken: ""
  modelName: ""

# Contains all model details: external/internal, API key requirements, service mappings
modelConfig: {}


rbac:
  createGrafanaRole: true # User sets this to false if role already exists

