# This chart now only deploys backend services (llm-service, llama-stack, pgvector)
# RAG UI components have been removed

# Common model values for llm-service and llama-stack
# See format in https://github.com/RHEcosystemAppEng/ai-architecture-charts/blob/main/helm/llm-service/values.yaml
# For e.g., to add a new model add the following block and it will append to the list of models defined in the llm-service

global:
  models: {}


pgvector:
  secret:
    user: postgres
    password: rag_password
    dbname: rag_blueprint
    host: pgvector
    port: "5432"

minio:
  secret:
    user: minio_rag_user
    password: minio_rag_password
    host: minio
    port: "9000"
  
    # Upload sample files to the minio bucket 
  sampleFileUpload:
    enabled: true
    bucket: documents
    urls: 
    - https://raw.githubusercontent.com/rh-ai-kickstart/RAG/refs/heads/main/notebooks/Zippity_Zoo_Grand_Invention.pdf
    - https://raw.githubusercontent.com/rh-ai-kickstart/RAG/refs/heads/main/notebooks/Zippity_Zoo_and_the_Town_of_Tumble_Town.pdf
    - https://raw.githubusercontent.com/rh-ai-kickstart/RAG/refs/heads/main/notebooks/Zippity_Zoo_and_the_Town_of_Whispering_Willows.pdf


llama-stack:
  env:
    - name: VLLM_MAX_TOKENS
      value: "4096"
    - name: VLLM_API_TOKEN
      value: fake
    - name: OTEL_ENDPOINT
      value: http://otel-collector-collector.observability-hub.svc.cluster.local:4318/v1/traces
    - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
      value: sqlite3
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          key: user
          name: pgvector
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: pgvector
    - name: POSTGRES_HOST
      valueFrom:
        secretKeyRef:
          key: host
          name: pgvector
    - name: POSTGRES_PORT
      valueFrom:
        secretKeyRef:
          key: port
          name: pgvector
    - name: POSTGRES_DBNAME
      valueFrom:
        secretKeyRef:
          key: dbname
          name: pgvector
  secrets:
    TAVILY_SEARCH_API_KEY: "Paste-your-key-here"
  mcp-servers: {}
    #  mcp-weather:
    #   uri: http://rag-mcp-weather:8000/sse


ingestion-pipeline:
  # options are [S3, URL]
  source: S3
  # embedding model to use for creating embeddings
  embedding_model: all-MiniLM-L6-v2
  # name of the vector db with version, pipeline will be created with pipeline_red_hat_openshift
  name: "zippity-zoo-vector-db"
  # version of the knowledgebase
  version: "1.0"

  S3:
    access_key_id: minio_rag_user
    secret_access_key: minio_rag_password
    bucket_name: documents
    endpoint_url: http://minio:9000
    region: us-east-1
